project:
  type: website
  output-dir: docs
website:
  title: "Liu Meihan NM2207"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Final Project"     
        menu: 
        - data_description.qmd
        - project.qmd
        - story.qmd
      
      

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

