project:
  type: website
  output-dir: docs
website:
  title: "LiuMeihan124.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd

format:
  html:
    theme: jekyll-theme-lux
    css: styles.css
    toc: true

editor: visual

