---
title: "Data Analysis"
---

## Types of social media influencers

According to Campbell and Farrell (2020), they've introduced a valuable typology comprising five distinct SMI categories. These categories are delineated by the scale of their followings, with celebrity influencers and mega-influencers boasting the largest follower counts (over 1 million), followed by macro-influencers (ranging from 100,000 to one million), micro-influencers (between 10,000 and 100,000), and nano-influencers (under 10,000).

```{=html}
<iframe height="400" width="100%" frameborder="no" src="https://liumeihan124.shinyapps.io/sizes_app/"> </iframe>
```
In the analyzed period from June to December 2022, notable trends emerged in the distribution of influencers across different categories. In June 2022, the dataset comprised 777 mega influencers, 173 macro influencers, 39 micro influencers and 11 nano influencers. By September 2022, the number of mega influencers rose to 795, while macro influencers decreased to 162, micro influencers decreased to 38 and nano influencers decreased to 5. Finally, in December 2022, the trend continued, with an increase in mega influencers to 860, a decrease in macro influencers to 119, and a decrease in micro influencers to 21. Notably, there were no nano influencers included in the dataset for this month. These fluctuations shed light on the dynamic nature of influencer engagement over time.

## Views vs. Engagement metrics

There is often a correlation between social media views and engagement metrics. Higher views typically indicate increased exposure and potential reach, which can lead to higher levels of engagement such as likes, comments, shares, and click-through rates. However, the strength of this correlation can vary depending on factors such as the quality of content, audience demographics, platform algorithms, and promotional strategies. Research in this area suggests that while a strong correlation exists in many cases, it is not always definitive and can be influenced by various contextual factors.

```{=html}
<iframe height="400" width="100%" frameborder="no" src="https://liumeihan124.shinyapps.io/relationship_app/"> </iframe>
```
There is a strong positive correlation between views and likes, with an average correlation coefficient value of (0.84 + 0.75 + 0.75) / 3 = [**0.78**]{.underline}, indicating that an increase in views tends to correspond to more likes. However, there is only a weak positive correlation between views and shares, with an average correlation coefficient value of (0.4 + 0.14 + 0.35) / 3 = [**0.30**]{.underline} (rounded to the nearest two decimals). This suggests that the number of views does not strongly relate to the number of shares. Similarly, there is also a weak positive correlation between views and comments, with an average correlation coefficient value of (0.56 + 0.41 + 0.41) / 3 = [**0.46**]{.underline}, indicating that the number of views does not significantly relate to the number of comments.

## Likes vs. Engagement metrics

While views may serve to increase exposure and potentially enhance engagement metrics, such as likes, shares, and comments, it's noteworthy that likes often represent a direct reaction from the audience. This immediate feedback mechanism could likewise influence similar interactions, such as shares and comments, reflecting a broader spectrum of engagement beyond mere viewership numbers. This suggests that while views contribute to the overall reach and visibility of content, the depth of engagement, as indicated by likes and subsequent actions, provides valuable insights into audience sentiment and involvement with the material. Consequently, understanding the nuanced relationship between views and engagement metrics can aid content creators in crafting more impactful and resonant social media strategies.

```{=html}
<iframe height="400" width="100%" frameborder="no" src=" https://liumeihan124.shinyapps.io/relationship2_app/"> </iframe>
```
The robust positive correlation between likes and views, previously highlighted with an average coefficient of [0.78]{.underline}, underscores the strong connection between audience appreciation and content visibility. However, when examining the relationship between views and shares, the average correlation coefficient, calculated as (0.41 + 0.12 + 0.33) / 3 = [0.29]{.underline} (rounded to the nearest two decimals), suggests a weaker association between shares and views. In contrast, comments exhibit a moderate positive correlation with likes, as evidenced by the average coefficient of (0.64 + 0.46 + 0.51) / 3 = [0.54]{.underline} (rounded to the nearest two decimals). This indicates that likes may have a closer association with comments than with shares, suggesting differing levels of engagement across various interaction metrics.
